// Generated by gencpp from file exam2_ydimitri/TurtleActionGoal.msg
// DO NOT EDIT!


#ifndef EXAM2_YDIMITRI_MESSAGE_TURTLEACTIONGOAL_H
#define EXAM2_YDIMITRI_MESSAGE_TURTLEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <exam2_ydimitri/TurtleGoal.h>

namespace exam2_ydimitri
{
template <class ContainerAllocator>
struct TurtleActionGoal_
{
  typedef TurtleActionGoal_<ContainerAllocator> Type;

  TurtleActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  TurtleActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::exam2_ydimitri::TurtleGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleActionGoal_

typedef ::exam2_ydimitri::TurtleActionGoal_<std::allocator<void> > TurtleActionGoal;

typedef boost::shared_ptr< ::exam2_ydimitri::TurtleActionGoal > TurtleActionGoalPtr;
typedef boost::shared_ptr< ::exam2_ydimitri::TurtleActionGoal const> TurtleActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exam2_ydimitri

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "836ef6cd982b1986f5fe51fb56a3934a";
  }

  static const char* value(const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x836ef6cd982b1986ULL;
  static const uint64_t static_value2 = 0xf5fe51fb56a3934aULL;
};

template<class ContainerAllocator>
struct DataType< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam2_ydimitri/TurtleActionGoal";
  }

  static const char* value(const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TurtleGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 goal_x\n"
"float32 goal_y\n"
;
  }

  static const char* value(const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM2_YDIMITRI_MESSAGE_TURTLEACTIONGOAL_H
