// Generated by gencpp from file exam2_ydimitri/TurtleAction.msg
// DO NOT EDIT!


#ifndef EXAM2_YDIMITRI_MESSAGE_TURTLEACTION_H
#define EXAM2_YDIMITRI_MESSAGE_TURTLEACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <exam2_ydimitri/TurtleActionGoal.h>
#include <exam2_ydimitri/TurtleActionResult.h>
#include <exam2_ydimitri/TurtleActionFeedback.h>

namespace exam2_ydimitri
{
template <class ContainerAllocator>
struct TurtleAction_
{
  typedef TurtleAction_<ContainerAllocator> Type;

  TurtleAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  TurtleAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::exam2_ydimitri::TurtleActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::exam2_ydimitri::TurtleActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleAction_

typedef ::exam2_ydimitri::TurtleAction_<std::allocator<void> > TurtleAction;

typedef boost::shared_ptr< ::exam2_ydimitri::TurtleAction > TurtleActionPtr;
typedef boost::shared_ptr< ::exam2_ydimitri::TurtleAction const> TurtleActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam2_ydimitri::TurtleAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exam2_ydimitri::TurtleAction_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exam2_ydimitri::TurtleAction_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exam2_ydimitri

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7cef25e03df33f362bca681e9ac626a";
  }

  static const char* value(const ::exam2_ydimitri::TurtleAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7cef25e03df33f3ULL;
  static const uint64_t static_value2 = 0x62bca681e9ac626aULL;
};

template<class ContainerAllocator>
struct DataType< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam2_ydimitri/TurtleAction";
  }

  static const char* value(const ::exam2_ydimitri::TurtleAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"TurtleActionGoal action_goal\n"
"TurtleActionResult action_result\n"
"TurtleActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TurtleGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 goal_x\n"
"float32 goal_y\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TurtleResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"duration elapsed_time\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TurtleFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: exam2_ydimitri/TurtleFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"duration elapsed_time\n"
"\n"
;
  }

  static const char* value(const ::exam2_ydimitri::TurtleAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam2_ydimitri::TurtleAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam2_ydimitri::TurtleAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::exam2_ydimitri::TurtleActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::exam2_ydimitri::TurtleActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::exam2_ydimitri::TurtleActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM2_YDIMITRI_MESSAGE_TURTLEACTION_H
