// Generated by gencpp from file exam2_ydimitri/TurtleGoal.msg
// DO NOT EDIT!


#ifndef EXAM2_YDIMITRI_MESSAGE_TURTLEGOAL_H
#define EXAM2_YDIMITRI_MESSAGE_TURTLEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exam2_ydimitri
{
template <class ContainerAllocator>
struct TurtleGoal_
{
  typedef TurtleGoal_<ContainerAllocator> Type;

  TurtleGoal_()
    : goal_x(0.0)
    , goal_y(0.0)  {
    }
  TurtleGoal_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)  {
  (void)_alloc;
    }



   typedef float _goal_x_type;
  _goal_x_type goal_x;

   typedef float _goal_y_type;
  _goal_y_type goal_y;





  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleGoal_

typedef ::exam2_ydimitri::TurtleGoal_<std::allocator<void> > TurtleGoal;

typedef boost::shared_ptr< ::exam2_ydimitri::TurtleGoal > TurtleGoalPtr;
typedef boost::shared_ptr< ::exam2_ydimitri::TurtleGoal const> TurtleGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator1> & lhs, const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exam2_ydimitri

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9aa8c2e2b21fc8544d27640eeac21d97";
  }

  static const char* value(const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9aa8c2e2b21fc854ULL;
  static const uint64_t static_value2 = 0x4d27640eeac21d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam2_ydimitri/TurtleGoal";
  }

  static const char* value(const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 goal_x\n"
"float32 goal_y\n"
;
  }

  static const char* value(const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam2_ydimitri::TurtleGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam2_ydimitri::TurtleGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<float>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<float>::stream(s, indent + "  ", v.goal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM2_YDIMITRI_MESSAGE_TURTLEGOAL_H
