; Auto-generated. Do not edit!


(cl:in-package exam2_ydimitri-msg)


;//! \htmlinclude TurtleGoal.msg.html

(cl:defclass <TurtleGoal> (roslisp-msg-protocol:ros-message)
  ((goal_x
    :reader goal_x
    :initarg :goal_x
    :type cl:float
    :initform 0.0)
   (goal_y
    :reader goal_y
    :initarg :goal_y
    :type cl:float
    :initform 0.0))
)

(cl:defclass TurtleGoal (<TurtleGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurtleGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurtleGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name exam2_ydimitri-msg:<TurtleGoal> is deprecated: use exam2_ydimitri-msg:TurtleGoal instead.")))

(cl:ensure-generic-function 'goal_x-val :lambda-list '(m))
(cl:defmethod goal_x-val ((m <TurtleGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exam2_ydimitri-msg:goal_x-val is deprecated.  Use exam2_ydimitri-msg:goal_x instead.")
  (goal_x m))

(cl:ensure-generic-function 'goal_y-val :lambda-list '(m))
(cl:defmethod goal_y-val ((m <TurtleGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exam2_ydimitri-msg:goal_y-val is deprecated.  Use exam2_ydimitri-msg:goal_y instead.")
  (goal_y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurtleGoal>) ostream)
  "Serializes a message object of type '<TurtleGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'goal_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'goal_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurtleGoal>) istream)
  "Deserializes a message object of type '<TurtleGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_x) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_y) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurtleGoal>)))
  "Returns string type for a message object of type '<TurtleGoal>"
  "exam2_ydimitri/TurtleGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurtleGoal)))
  "Returns string type for a message object of type 'TurtleGoal"
  "exam2_ydimitri/TurtleGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurtleGoal>)))
  "Returns md5sum for a message object of type '<TurtleGoal>"
  "9aa8c2e2b21fc8544d27640eeac21d97")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurtleGoal)))
  "Returns md5sum for a message object of type 'TurtleGoal"
  "9aa8c2e2b21fc8544d27640eeac21d97")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurtleGoal>)))
  "Returns full string definition for message of type '<TurtleGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 goal_x~%float32 goal_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurtleGoal)))
  "Returns full string definition for message of type 'TurtleGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 goal_x~%float32 goal_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurtleGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurtleGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TurtleGoal
    (cl:cons ':goal_x (goal_x msg))
    (cl:cons ':goal_y (goal_y msg))
))
